export const CAT_COLORS = {
  "Poulet": { bg: "#FFF3E0", text: "#E65100", border: "#FFB74D" },
  "Bœuf": { bg: "#FFEBEE", text: "#B71C1C", border: "#EF9A9A" },
  "Viande transformée": { bg: "#FCE4EC", text: "#880E4F", border: "#F48FB1" },
  "Légumes": { bg: "#E8F5E9", text: "#1B5E20", border: "#81C784" },
  "Poisson": { bg: "#E3F2FD", text: "#0D47A1", border: "#64B5F6" },
  "Produit d'épicerie": { bg: "#FFF8E1", text: "#F57F17", border: "#FFD54F" },
  "Produits laitiers": { bg: "#F3E5F5", text: "#6A1B9A", border: "#CE93D8" },
  "Huile": { bg: "#FFFDE7", text: "#827717", border: "#DCE775" },
  "Pâte": { bg: "#FBE9E7", text: "#BF360C", border: "#FFAB91" },
  "Emballage": { bg: "#ECEFF1", text: "#37474F", border: "#90A4AE" },
  "Gaz": { bg: "#E0F7FA", text: "#006064", border: "#4DD0E1" },
  "Carburant": { bg: "#EFEBE9", text: "#4E342E", border: "#A1887F" },
  "Main d'œuvre": { bg: "#EDE7F6", text: "#4527A0", border: "#9575CD" },
  "Non classé": { bg: "#F5F5F5", text: "#616161", border: "#BDBDBD" },
};

export function catColor(cat) {
  return CAT_COLORS[cat] || CAT_COLORS["Non classé"];
}

export const DEFAULT_PRODUCTS = [
  { name: "Viande hachée poulet", category: "Poulet" },
  { name: "Poulet complet", category: "Poulet" },
  { name: "Viande Hachée Bœuf", category: "Bœuf" },
  { name: "Dinde fumée", category: "Viande transformée" },
  { name: "Carottes", category: "Légumes" },
  { name: "Epinards", category: "Légumes" },
  { name: "Champignons noirs", category: "Légumes" },
  { name: "Champignons frais", category: "Légumes" },
  { name: "Oignons", category: "Légumes" },
  { name: "Citron", category: "Légumes" },
  { name: "Citron Confit", category: "Légumes" },
  { name: "Persil et coriandre", category: "Légumes" },
  { name: "Poivron rouge et jaune", category: "Légumes" },
  { name: "Poirreau", category: "Légumes" },
  { name: "Courgette", category: "Légumes" },
  { name: "Crevettes roses", category: "Poisson" },
  { name: "Crevettes Grises 60/70", category: "Poisson" },
  { name: "Merlan", category: "Poisson" },
  { name: "Sépia", category: "Poisson" },
  { name: "Gingembre frais", category: "Produit d'épicerie" },
  { name: "Poivre noir", category: "Produit d'épicerie" },
  { name: "Soja Epaisse", category: "Produit d'épicerie" },
  { name: "Soja légère", category: "Produit d'épicerie" },
  { name: "Huile de sésame", category: "Produit d'épicerie" },
  { name: "Sweet chili sauce", category: "Produit d'épicerie" },
  { name: "Sauce Tériyaki", category: "Produit d'épicerie" },
  { name: "Sauce huitres", category: "Produit d'épicerie" },
  { name: "Sauce poisson", category: "Produit d'épicerie" },
  { name: "Sel chinois", category: "Produit d'épicerie" },
  { name: "Ail poudre", category: "Produit d'épicerie" },
  { name: "Ail", category: "Produit d'épicerie" },
  { name: "Harissa Poudre", category: "Produit d'épicerie" },
  { name: "Harissa", category: "Produit d'épicerie" },
  { name: "Thym", category: "Produit d'épicerie" },
  { name: "Chapelure", category: "Produit d'épicerie" },
  { name: "Œufs", category: "Produit d'épicerie" },
  { name: "Piment doux", category: "Produit d'épicerie" },
  { name: "Knorr poisson", category: "Produit d'épicerie" },
  { name: "Knorr Poulet", category: "Produit d'épicerie" },
  { name: "Knorr safran", category: "Produit d'épicerie" },
  { name: "Feuille de Laurier", category: "Produit d'épicerie" },
  { name: "Vermicelle", category: "Produit d'épicerie" },
  { name: "Vermicelle 250Gr", category: "Produit d'épicerie" },
  { name: "Curcuma poudre", category: "Produit d'épicerie" },
  { name: "Gingembre poudre", category: "Produit d'épicerie" },
  { name: "Canelle poudre", category: "Produit d'épicerie" },
  { name: "Amandes", category: "Produit d'épicerie" },
  { name: "Sucre semoule", category: "Produit d'épicerie" },
  { name: "Fleur d'orange", category: "Produit d'épicerie" },
  { name: "Beurre animale", category: "Produits laitiers" },
  { name: "Fromage Blanc Jben INDUS", category: "Produits laitiers" },
  { name: "Smen", category: "Produits laitiers" },
  { name: "Huile d'olive", category: "Huile" },
  { name: "Huile de table Tournesol", category: "Huile" },
  { name: "Feuille de brick", category: "Pâte" },
  { name: "Emballage", category: "Emballage" },
  { name: "Carton pâtissier", category: "Emballage" },
  { name: "Etiquettes", category: "Emballage" },
  { name: "Bota Gaz", category: "Gaz" },
  { name: "Diesel", category: "Carburant" },
  { name: "Main d'œuvre", category: "Main d'œuvre" },
];

export const UNITS = ["kg","g","L","unité","pack","carton","pièce","bouteille","sac","boîte","bidon","plateau"];
